version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 09:00
  open-pull-requests-limit: 10
  groups:
    python-minor:
      update-types:
      - minor
      - patch
      patterns:
      - '*'
  labels:
  - dependencies
  - python
  reviewers:
  - ameoblius-ai
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 09:00
  open-pull-requests-limit: 10
  groups:
    actions-minor:
      update-types:
      - minor
      - patch
      patterns:
      - '*'
  labels:
  - dependencies
  - github-actions
  reviewers:
  - ameoblius-ai
